<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<LangVersion>latest</LangVersion>

		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyName>lammas123.MoreSettings</AssemblyName>
		<Product>MoreSettings</Product>
		<Version>1.2.1</Version>

		<AutoLaunchDir Condition="'$(AutoLaunchDir)' == ''">lammas123-MoreSettings</AutoLaunchDir>
		<SteamPath Condition="'$(SteamPath)' == ''">S:/Steam/steam.exe</SteamPath>

		<ProfileDir Condition="'$(ProfileDir)' == ''">C:/Users/lamma/AppData/Roaming/r2modmanPlus-local/CrabGame/profiles/modded</ProfileDir>
		<UnhollowedDir>$(ProfileDir)/BepInEx/unhollowed</UnhollowedDir>
		<DepsDir Condition="'$(DepsDir)' == ''">C:/Users/lamma/source/repos/Crab Game</DepsDir>
	</PropertyGroup>


	<!-- Configurations -->
	<PropertyGroup>
		<Configurations>Debug;Release</Configurations>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>embedded</DebugType>

		<!-- Trim the path to just include the project in stack traces -->
		<PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>

		<AutoLaunch>true</AutoLaunch>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugSymbols>false</DebugSymbols>
		<DebugType>none</DebugType>

		<!-- Trim the path to just include the project in stack traces -->
		<PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>

		<AutoLaunch>false</AutoLaunch>
	</PropertyGroup>


	<!-- Checks -->
	<Target Name="CheckUnhollowed" BeforeTargets="ResolveAssemblyReferences">
		<Error Condition="!Exists('$(UnhollowedDir)/Assembly-CSharp.dll')" Text="Unhollowed assemblies not found. Verify $(UnhollowedDir) (your .csproj's UnhollowedDir) is correct and run BepInEx Il2Cpp unhollowing first." />
	</Target>

	<Target Name="CheckDeps" BeforeTargets="ResolveAssemblyReferences" Condition="'$(DepsDir)' != ''">
		<Error Condition="!Exists('$(DepsDir)')" Text="$(DepsDir) does not exist, correct your DepsDir within your .csproj." />
	</Target>


	<!-- Building -->
	<ItemGroup>
		<Compile Remove="Thunderstore/**" />
		<EmbeddedResource Remove="Thunderstore/**" />
		<None Remove="Thunderstore/**" />
	</ItemGroup>

	<Target Name="ClearReferenceCopyLocalPaths" AfterTargets="ResolveAssemblyReferences">
		<ItemGroup>
			<ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" />
		</ItemGroup>
	</Target>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(AutoLaunch)' == 'true'">
		<MakeDir Directories="$(ProfileDir)/BepInEx/plugins/$(AutoLaunchDir)" Condition="!Exists('$(ProfileDir)/BepInEx/plugins/$(AutoLaunchDir)')" />

		<Copy SourceFiles="$(OutDir)$(AssemblyName).dll"
			  DestinationFiles="$(ProfileDir)/BepInEx/plugins/$(AutoLaunchDir)/$(AssemblyName).dll"
			  SkipUnchangedFiles="true" />

		<Exec Command="$(SteamPath) steam://rungameid/1782210" Condition="Exists('$(SteamPath)')" />
		<Warning Condition="!Exists('$(SteamPath)')" Text="The Steam path $(SteamPath) does not exist." />
	</Target>

	<Target Name="Thunderstore" AfterTargets="PostBuildEvent" Condition="'$(Configuration)' == 'Release'">
		<Copy SourceFiles="$(OutDir)$(AssemblyName).dll"
		      DestinationFiles="$(MSBuildProjectDirectory)/Thunderstore/$(Product)/BepInEx/plugins/$(AssemblyName).dll"
			  Condition="Exists('$(MSBuildProjectDirectory)/Thunderstore/$(Product)/BepInEx/plugins')"
			  SkipUnchangedFiles="true" />

		<Warning Condition="!Exists('$(MSBuildProjectDirectory)/Thunderstore/$(Product)/BepInEx/plugins')" Text="The Thunderstore directory $(MSBuildProjectDirectory)/Thunderstore/$(Product)/BepInEx/plugins does not exist." />
	</Target>


	<!-- Dependencies -->
	<ItemGroup>
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" PrivateAssets="all" Version="0.4.1">
			<!-- Suppress CS0436: AssemblyPublicizer IgnoresAccessChecksToAttribute conflicts with MonoMod.Utils, this is safe to ignore -->
			<NoWarn>$(NoWarn);CS0436</NoWarn>
		</PackageReference>

		<PackageReference Include="BepInEx.PluginInfoProps" Version="2.1.0" />

		<PackageReference Include="BepInEx.IL2CPP" Version="6.0.0-*" />
		<PackageReference Include="BepInEx.Preloader.Core" Version="6.0.0-*" />
	</ItemGroup>

	<ItemGroup>
		<!-- BepInEx Assemblies -->
		<Reference Include="0Harmony" Publicize="true">
			<HintPath>$(ProfileDir)/BepInEx/core/0Harmony.dll</HintPath>
		</Reference>

		<!-- Game Assemblies -->
		<Reference Include="Assembly-CSharp">
			<HintPath>$(UnhollowedDir)/Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp-firstpass">
			<HintPath>$(UnhollowedDir)/Assembly-CSharp-firstpass.dll</HintPath>
		</Reference>
		
		<Reference Include="DissonanceVoip" Publicize="true">
			<HintPath>$(UnhollowedDir)/DissonanceVoip.dll</HintPath>
		</Reference>

		<!-- Il2Cpp Assemblies -->
		<Reference Include="Il2Cppmscorlib">
			<HintPath>$(UnhollowedDir)/Il2Cppmscorlib.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem">
			<HintPath>$(UnhollowedDir)/Il2CppSystem.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Core">
			<HintPath>$(UnhollowedDir)/Il2CppSystem.Core.dll</HintPath>
		</Reference>

		<!-- Other Mod Assemblies -->
		<!--<Reference Include="CrabDevKit">
			<HintPath>$(DepsDir)/CrabDevKit/bin/Release/netstandard2.1/lammas123.CrabDevKit.dll</HintPath>
		</Reference>-->

		<!-- Unity Assemblies-->
		<Reference Include="UnityEngine.AnimationModule">
			<HintPath>$(UnhollowedDir)/UnityEngine.AnimationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AudioModule">
			<HintPath>$(UnhollowedDir)/UnityEngine.AudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>$(UnhollowedDir)/UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
			<HintPath>$(UnhollowedDir)/UnityEngine.InputLegacyModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ParticleSystemModule">
			<HintPath>$(UnhollowedDir)/UnityEngine.ParticleSystemModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
			<HintPath>$(UnhollowedDir)/UnityEngine.PhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextRenderingModule">
			<HintPath>$(UnhollowedDir)/UnityEngine.TextRenderingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UI">
			<HintPath>$(UnhollowedDir)/UnityEngine.UI.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIModule">
			<HintPath>$(UnhollowedDir)/UnityEngine.UIModule.dll</HintPath>
		</Reference>

		<Reference Include="Unity.PostProcessing.Runtime">
			<HintPath>$(UnhollowedDir)/Unity.PostProcessing.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
			<HintPath>$(UnhollowedDir)/Unity.TextMeshPro.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>